### PR TITLE
Fix links

### LINKED ISSUE #17: Resolve images paths in READMEs
expected: https://github.com/dkurt/openvino_practice/tree/master/modules/1_opencv

got: 

---
image

### PR DESCRIPTION
**Pull request by dkurt**
Now local paths to images are replaced to global ones

### CODE REVIEW

File: server/index.js [hunk 1]
```diff
@@ -89,8 +106,16 @@ function listRepos(token, user_name, callback) {
...
         }
       }
+
+      // Modify project URL so it can be used for direct access to images
+      project_url = project_url.replace('github.com', 'raw.githubusercontent.com') + '/master/'
+
       tasks.forEach(task => {
         fs.readFile('node_modules/' + project + '/' + task.description, 'utf8', (err, file_data) => {
+          // Replace all links excluding ones which start with http/https
+          file_data = file_data.replace(/(src=['"]|\!\[.*\]\()(?!http)(.*?)(['")])/g, (data, prefix, link, suffix) => {
```
Comment (dkurt) [inline server/index.js:116]: regex is the most magic stuff ever :rainbow: :mage_man: :unicorn:
